version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: inventory-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: token_management_db
      MYSQL_USER: inventory
      MYSQL_PASSWORD: inventory123
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
