server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    relaxed-query-chars: ['[', ']']

spring:
  application:
    name: registration-service
  
  datasource:
    url: jdbc:mariadb://localhost:3307/registration_db
    driverClassName: org.mariadb.jdbc.Driver
    username: inventory
    password: inventory123
  
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  security:
    user:
      name: admin
      password: admin123

# Token Management Service Configuration
token-service:
  base-url: http://localhost:8081
  endpoints:
    tokens: /api/tokens
    accounts: /api/accounts

# Platform-specific configurations
platforms:
  naver:
    api-base-url: https://api.commerce.naver.com
    endpoints:
      products: /products
      categories: /categories
  cafe24:
    api-base-url: https://your-store.cafe24api.com
    endpoints:
      products: /admin/products
      categories: /admin/categories
  coupang:
    api-base-url: https://api-gateway.coupang.com
    endpoints:
      products: /v2/providers/affiliate_open_api/apis/openapi/products
  bunjang:
    base-url: https://m.bunjang.co.kr
    endpoints:
      login: /login
      products: /products
  danggeun:
    base-url: https://www.danggeunmarket.com
    endpoints:
      login: /login
      products: /products

# Web automation settings
automation:
  browser:
    headless: true
    timeout: 30000
    window-size: "1920,1080"
  retry:
    max-attempts: 3
    delay: 1000

logging:
  level:
    com.inventory.registration: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

