spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

# Test Configuration
encryption:
  key: myEncryptionKey123456789012345678901234567890

oauth:
  naver:
    token-url: https://test.naver.com/oauth2.0/token
  cafe24:
    token-url: https://test.cafe24.com/api/v2/oauth/token
  coupang:
    token-url: https://test.coupang.com/token

